name: Compile Protocols

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  compile:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Configure Git User
      run: |
        git config --global user.name 'EreboPSilva'
        git config --global user.email 'ereboperezsilva@ebi.ac.uk'
    
    - name: Compile Protocols
      run: |
        # Create the "protocols" directory if it doesn't exist
        mkdir -p protocols
        
        # Compile the "map" protocol
        cat \
          methods/genome_preparation.md \
          methods/repeat_elements.md \
          methods/simple_features.md \
          methods/projection.md \
          methods/homology.md \
          methods/transcriptomic.md \
          methods/finalization.md \
          methods/pseudogenes.md \
          > protocols/map.md
        
         # Compile the "map_np" protocol
         cat \
          methods/genome_preparation.md \
          methods/repeat_elements.md \
          methods/simple_features.md \
          methods/homology.md \
          methods/transcriptomic.md \
          methods/finalization.md \
          methods/pseudogenes.md \
          > protocols/map_np.md
            
        # Compile the "map_rm" protocol
        cat \
          methods/genome_preparation.md \
          methods/repeat_elements.md \
          methods/repeat_modeler.md \
          methods/simple_features.md \
          methods/projection.md \
          methods/homology.md \
          methods/transcriptomic.md \
          methods/finalization.md \
          methods/pseudogenes.md \
          > protocols/map_rm.md

        # Compile the "rap" protocol
        cat \
          methods/genome_preparation.md \
          methods/repeat_elements.md \
          methods/repeat_modeler.md \
          methods/simple_features.md \
          methods/projection.md \
          methods/homology.md \
          methods/transcriptomic.md \
          methods/finalization.md \
          > protocols/rap.md

        # Compile the "boa" protocol
        cat \
          methods/genome_preparation.md \
          methods/repeat_elements.md \
          methods/repeat_modeler.md \
          methods/simple_features.md \
          methods/projection.md \
          methods/homology.md \
          methods/finalization.md \
          > protocols/boa.md

    - name: Sync!
      run: |
        # Add the compiled protocols to the Git repo
        git add protocols/
        git commit -m "Compile protocols"
        git push
